apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb-https
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP