apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: nginx-https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer